server:
  port: 8100
spring:
  application:
    name: app-eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
    fetch-registry: true
    register-with-eureka: true